export const GET_TEACHER_REQUEST = "GET_TEACHER_REQUEST";
export const GET_TEACHER_SUCCESS = "GET_TEACHER_SUCCESS";
export const GET_TEACHER_FAILED = "GET_TEACHER_FAILED";

export const GET_CLASS_REQUEST = "GET_CLASS_REQUEST";
export const GET_CLASS_SUCCESS = "GET_CLASS_SUCCESS";
export const GET_CLASS_FAILED = "GET_CLASS_FAILED";
